#Reference1 : https://actions-pipeline.readthedocs.io/en/latest/
#Reference2 : https://actions-pipeline.readthedocs.io/en/latest/
name: Update database

on:
  push:
  workflow_dispatch:
  schedule : 
    - cron : '0 0 * * 0'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python get_latest_video_data.py
        
      - name: Commit and push if it changed
        run: |-
          git config user.name "clara8043"
          git config user.email "clara8043@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
